### ISSUE TITLE
p_classification运行出错

### ISSUE THREAD

**Issue by AaronWhite95** [baidu/information-extraction#1]
直接运行命令`python bin/p_classification/p_train.py --conf_path=./conf/IE_extraction.conf`，
代码报错如下，请问是为什么（对paddlepaddle还不太熟，报错不太会处理，想先把baseline跑起来，谢谢）
`W0309 22:57:00.700938 37327 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.0, Runtime API Version: 9.0
W0309 22:57:00.701022 37327 device_context.cc:271] device: 0, cuDNN Version: 5.0.
W0309 22:57:00.701028 37327 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 5.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "bin/p_classification/p_train.py", line 149, in <module>
    main(conf_dict, use_cuda=use_gpu)
  File "bin/p_classification/p_train.py", line 137, in main
    train(conf_dict, data_generator, use_cuda=use_cuda)
  File "bin/p_classification/p_train.py", line 122, in train
    train_loop(fluid.default_main_program())
  File "bin/p_classification/p_train.py", line 79, in train_loop
    exe.run(fluid.default_startup_program())
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1382, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/initializer.py", line 167, in __call__
    stop_gradient=True)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1198, in create_var
    kwargs['initializer'](var, self)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 402, in set_variable_initializer
    initializer=initializer)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 137, in create_global_var
    value=float(value), force_cpu=force_cpu))
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 92, in _create_global_learning_rate
    persistable=True)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 224, in _create_optimization_pass
    self._create_global_learning_rate()
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 350, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/home/xfbai/anaconda3/envs/py2/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 405, in minimize
    optimize_ops = self.apply_gradients(params_grads)
  File "bin/p_classification/p_train.py", line 65, in train
    sgd_optimizer.minimize(avg_cost)
  File "bin/p_classification/p_train.py", line 137, in main
    train(conf_dict, data_generator, use_cuda=use_cuda)
  File "bin/p_classification/p_train.py", line 149, in <module>
    main(conf_dict, use_cuda=use_gpu)`

**Comment by hweidream** [comment]
看错误提示是你安装的paddlepaddle和cudnn的版本不兼容，可以尝试升级下cudnn

**Comment by AaronWhite95** [comment]
但我运行简单的paddlepaddle例程是可以跑通的
![image](https://user-images.githubusercontent.com/19512779/54080137-84f45700-4324-11e9-9f12-10c2407aa408.png)
版本应该是没有问题的啊

**Comment by hweidream** [comment]
这个需要用paddle1.2，现在官网默认安装的是paddle1.3，确认版本是正确的？如果尝试过不行，可以在官网中扫码入群，群里有paddle部门的同学来解答这类问题

**Comment by AaronWhite95** [comment]
版本是paddlepaddle-gpu 1.3.0.post97，应该是符合要求的

**Comment by hweidream** [comment]
安装下paddlepaddle v1.2，目前的代码仅在1.2下测试过

**Comment by Wangpeiyi9979** [comment]
请问找到解决方案了吗。。

**Comment by Cantoria** [comment]
我的CUDA版本是9.1，CUDNN版本是7，运行实例时也是莫名报错：
`ARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 5.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.`
但是我查看CUDNN版本：
`cat $CUDA_HOME/include/cudnn.h | grep CUDNN_MAJOR -A 2
`
显示：
`#define CUDNN_MAJOR 7`
请高手解答，是不是要重装paddle？
