### ISSUE TITLE
 该代码是Python2还是Python3??为什么我两个都用了还是在报错?

### ISSUE THREAD

**Issue by jtyoui** [baidu/information-extraction#19]
```Python
(env) [root@localhost information-extraction]# python bin/p_classification/p_train.py --conf_path=./conf/IE_extraction.conf
Traceback (most recent call last):
  File "bin/p_classification/p_train.py", line 28, in <module>
    import paddle
  File "/mnt/information-extraction/env/lib64/python2.7/site-packages/paddle/__init__.py", line 25, in <module>
    import paddle.dataset
  File "/mnt/information-extraction/env/lib64/python2.7/site-packages/paddle/dataset/__init__.py", line 25, in <module>
    import paddle.dataset.sentiment
  File "/mnt/information-extraction/env/lib64/python2.7/site-packages/paddle/dataset/sentiment.py", line 29, in <module>
    import nltk
  File "/mnt/information-extraction/env/lib/python2.7/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "/mnt/information-extraction/env/lib/python2.7/site-packages/nltk/collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "/mnt/information-extraction/env/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
```

**Comment by hweidream** [comment]
代码是python2的，但你这个报错信息是import nltk的错误，应该是paddle安装的问题

**Comment by jtyoui** [comment]
> 代码是python2的，但你这个报错信息是import nltk的错误，应该是paddle安装的问题

确实是这样,我刚刚在nltk官方网站了解到了,需要安装底版本,比如nltk==3.3.非常感谢

**Comment by jtyoui** [comment]
有没有考虑用Python3.7来重写代码??

**Comment by hweidream** [comment]
近期内没有改造py3的计划
