### ISSUE TITLE
get_vocab.py运行出错

### ISSUE THREAD

**Issue by bigcat2333** [baidu/information-extraction#5]
您好，在运行get_vocab.py时报出错误
Traceback (most recent call last):
  File "lib/get_vocab.py", line 89, in <module>
    get_vocab(train_file, dev_file)
  File "lib/get_vocab.py", line 61, in get_vocab
    raise ValueError('The length of dev word is 0')
ValueError: The length of dev word is 0
想请教一下这个该如何解决呢？

**Comment by hweidream** [comment]
这个异常是因为从dev_data.json中读数据异常，你检查下这个文件的编码等问题，可以debug下get_vocab.py中的load_word_file函数看看

**Comment by KwokQian** [comment]
可以将第70行的代码，print word[0]改成 print word[0].encode('utf-8') 就可以解决了

**Comment by taotao033** [comment]
> 您好，在运行get_vocab.py时报出错误
> Traceback (most recent call last):
> File "lib/get_vocab.py", line 89, in 
> get_vocab(train_file, dev_file)
> File "lib/get_vocab.py", line 61, in get_vocab
> raise ValueError('The length of dev word is 0')
> ValueError: The length of dev word is 0
> 想请教一下这个该如何解决呢？

I guess that you also use python3. I delete decode('utf-8'), and fix it. You can try do it.
